title: 360<sup>o</sup> Surface Regression with a Hyper-sphere Loss
description: 
show_downloads: true
theme: jekyll-theme-slate
markdown: kramdown


github:
  models_url: https://github.com/VCL3D/HyperSphereSurfaceRegression/releases/tag/1.0
  data_url: https://vcl3d.github.io/3D60/
  owner_url: https://ankarako.github.io
  owner_name: Antonis Karakottas
  
google_analytics: UA-147231916-1
