title: 360<sup>o</sup> Surface Regression with a Hyper-sphere Loss
description: 
show_downloads: true
theme: jekyll-theme-slate
markdown: kramdown


github:
  zip_url: http://example.com/download.zip
  tar_url: http://test.com/download.tar
  owner_url: https://ankarako.github.io
  owner_name: Antonis Karakottas
