title: 360<sup>o</sup> Surface Regression with a Hyper-sphere Loss
description: 
show_downloads: true
theme: jekyll-theme-slate
markdown: kramdown


github:
  models_url: http://example.com/download.zip
  data_url: https://vcl3d.github.io/3D60/
  owner_url: https://ankarako.github.io
  owner_name: Antonis Karakottas
